//! Build script for ralphus-librarian: embeds the Windows resource (RAL-99)
//! and generates the embedded board-asset table (`board_assets.rs`) that the
//! release exe serves from memory.

use std::{env, fs, path::Path};

#[path = "src/asset_rules.rs"]
mod asset_rules;

fn main() {
    embed_resource::compile("windows_resource.rc", embed_resource::NONE)
        .manifest_optional()
        .unwrap();
    generate_board_assets();
}

/// Emits `$OUT_DIR/board_assets.rs`: a `BOARD_ASSETS` table of (route name,
/// file contents) pairs covering every board asset under `assets/` (the rules
/// live in `asset_rules.rs`, shared with the runtime dev-mode reader). Each
/// entry is embedded as an escaped string literal, so the release exe is
/// self-contained.
///
/// Build scripts talk to cargo on stdout (the `cargo:` directives); that is
/// the build script's product, not stray output, hence the allow.
#[allow(clippy::print_stdout)]
fn generate_board_assets() {
    let assets_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets");
    let out_dir = env::var("OUT_DIR").expect("cargo sets OUT_DIR");

    println!("cargo:rerun-if-changed={}", assets_root.display());

    let routes = asset_rules::collect_routes(&assets_root);

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from librarian/assets/ at compile time — do not edit.\n",
    );
    out.push_str("// Each entry is (route name, file contents); served by src/assets.rs.\n");
    out.push_str("pub static BOARD_ASSETS: &[(&str, &str)] = &[\n");
    for (name, path) in &routes {
        let contents =
            fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        out.push_str(&format!("    (\"{name}\", {:?}),\n", contents));
    }
    out.push_str("];\n");

    fs::write(Path::new(&out_dir).join("board_assets.rs"), out).expect("write board_assets.rs");
}
